exclude:        ['README.md', '_jekyll_s3.yml', 's3_website.yml', 'Gemfile', 'Gemfile.lock', 'readme.md', 'minify.sh']
markdown:       rdiscount
highlighter:    null
permalink:      /blog/:title

name:           Practical Jekyll
url:            https://www.practicaljekyll.com
description:    A technical book for the popular static website generator
copyright:      All rights reserved. 
email:          hello@practicaljekyll.com
twitter:        PracticalJekyll
assets:
    dirname: assets
    baseurl: /assets/
    css_compressor: yui
    js_compressor: yui
    sources:
        - _assets/javascripts
        - _assets/stylesheets
        - _assets/images
    cachebust: none
    cache: false
    debug: true
